### ISSUE TITLE
How to fix this isssue?

### ISSUE THREAD

**Issue by usamaasfar** [reactjs/react-basic#11]
There might be a problem with the project dependency tree.

It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

"babel-eslint": "9.0.0"

Don't try to install it manually: your package manager does it automatically.

However, a different version of babel-eslint was detected higher up in the tree:

C:\Users\chawki\node_modules\babel-eslint (version: 6.1.2)

Manually installing incompatible versions is known to cause hard-to-debug issues.

**Comment by Santrro** [comment]
@usama-asfar Your system has babel-eslint installed globally on "C:\Users\chawki\node_modules\babel-eslint", You need to uninstall this package globally or just visit this directory and delete this babel-eslint folder. After that in your react project directory run `npm i`. This will install correct version of babel-eslint as mentioned in package.json file of project.
