### ISSUE TITLE
Any channel for discussion?

### ISSUE THREAD

**Issue by kkpoon** [reactjs/react-basic#5]
for example: https://gitter.im/orgs/reactjs/rooms ?

**Comment by knowbody** [comment]
[Reactiflux](http://www.reactiflux.com/) is a good place for a discussion, it's a very popular place where React community hangs out.

**Comment by pieterv** [comment]
Also if you have an idea for a future React direction you could create a PR against https://github.com/reactjs/react-future

**Comment by zpao** [comment]
There isn't a single place. We're unlikely to use gitter. Discord has been great for the community but doesn't have a very strong presence from core-team members (signal/noise ratio is tough). There is a react-internals channel there which could be useful. We'll make some noise if we set up a definite destination for discussions around this.

**Comment by kkpoon** [comment]
Great. Thanks
